vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /uploads/images/posters
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        actor_photo:
            uri_prefix: /uploads/images/photos
            upload_destination: '%kernel.project_dir%/public/uploads/images/photos/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
